
spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.80.155
    port: 5672
    username: baboon
    password: baboon

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  routes:  # 这个是默认的配置, 这里可以注释掉
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  # 开启重试
  retryable: true

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

management:  # 暴露端点
  endpoints:
    web:
      exposure:
        include: hystrix.stream

# http://localhost:4001/hystrix  浏览器访问
# 监控端点  http://localhost:5001/turbine.stream